# Generated by Django 4.2.6 on 2023-11-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_custom_user_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Custom_user',
        ),
    ]
