# Generated by Django 4.2.6 on 2023-11-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0003_delete_custom_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=25)),
                ('desc', models.TextField()),
                ('domain', models.CharField(max_length=10)),
                ('stack', models.CharField(max_length=45)),
                ('link', models.URLField(null=True)),
                ('image', models.ImageField(upload_to='proj_imgs')),
                ('stud', models.CharField(max_length=25)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
