# Generated by Django 4.2.6 on 2023-11-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='full_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.CharField(max_length=25)),
                ('college', models.CharField(max_length=60)),
                ('sem', models.CharField(max_length=10)),
                ('photo', models.ImageField(null=True, upload_to='proj_imgs')),
                ('bio', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='stack',
            field=models.CharField(max_length=60),
        ),
    ]
