# Generated by Django 4.2.6 on 2023-11-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_full_user_alter_projects_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full_user',
            name='photo',
            field=models.ImageField(null=True, upload_to='user_imgs'),
        ),
    ]
