# Generated by Django 4.2.6 on 2023-11-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_full_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='full_user',
            name='github',
            field=models.URLField(null=True),
        ),
    ]
