# Generated by Django 4.2.6 on 2023-11-07 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0010_alter_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='likes',
            field=models.ManyToManyField(related_name='project_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
