# Generated by Django 4.2.6 on 2024-02-23 18:05

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_projects_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[600, 600], upload_to='proj_imgs'),
        ),
    ]
